### ISSUE TITLE
Nested functions not working

### ISSUE THREAD

**Issue by ThomasTram** [jmd-dk/cycept#1]
jit-compiling nested functions does not seem to work. For instance, the script

```python
import cycept
@cycept.jit(silent=False)
def nested_fun(x):
    return 2*x + 2.0
@cycept.jit(silent=False)
def fun1(x):
    return 0.5*nested_fun(2*x)
y = fun1(6.0)
print(y)
```
fails with the error message
```
Traceback (most recent call last):
  File "break_cycept.py", line 11, in <module>
    y = fun1(6.0)
  File "/lib/python3.10/site-packages/cycept/core.py", line 222, in wrapper
    func_compiled, result = transpile(func, wrapper, args, kwargs, **options)
  File "lib/python3.10/site-packages/cycept/core.py", line 299, in transpile
    result = record_locals(call)
  File "lib/python3.10/site-packages/cycept/core.py", line 525, in record_locals
    with hack_module_dict():
  File "lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "lib/python3.10/site-packages/cycept/core.py", line 520, in hack_module_dict
    call.module_dict.pop(cycept_module_refname)
KeyError: '__cycept__'
```

**Comment by jmd-dk** [comment]
Thanks for sharing this!
I have released version 0.0.6 which [includes a fix](https://github.com/jmd-dk/cycept/commit/07265da3b98e77b01ede34b38a9a6d5f346bdd38) for this bug.
